
export enum Edk2SymbolType {
    dscDefine,
    dscLibraryDefinition,
    dscModuleDefinition,
    dscSection,
    dscPcdDefinition,
    dscInclude,
    dscLine,
    infDefine,
    infSource,
    infPackage,
    infPpi,
    infProtocol,
    infPcd,
    infGuid,
    infDepex,
    infLibrary,
    infBinary,
    infSectionPackages,
    infSectionLibraries,
    infSectionProtocols,
    infSectionPpis,
    infSectionGuids,
    infSectionPcds,
    infSectionSource,
    infSection,
    infFunction,
    decSection,
    decDefine,
    decPackage,
    decPpi,
    decProtocol,
    decPcd,
    decInclude,
    decLibrary,
    decGuid,
    aslDefinitionBlock,
    aslExternal,
    aslScope,
    aslDevice,
    aslName,
    aslMethod,
    aslField,
    aslOpRegion,
    aslDefault,
    vfrDefault,
    vfrFormset,
    vfrForm,
    vfrOneof,
    vfrCheckbox,
    vfrString,
    vfrPassword,
    vfrNumeric,
    vfrGoto,
    fdfSection,
    fdfInf,
    fdfDefinition,
    fdfFile,
    fdfInclude,
    condition,
    unknown,
}

export var typeToStr: Map<Edk2SymbolType, string> = new Map(
    [
        [Edk2SymbolType.dscDefine, "dscDefine"],
        [Edk2SymbolType.dscLibraryDefinition, "dscLibraryDefinition"],
        [Edk2SymbolType.dscModuleDefinition, "dscModuleDefinition"],
        [Edk2SymbolType.dscSection, "dscSection"],
        [Edk2SymbolType.dscPcdDefinition, "dscPcdDefinition"],
        [Edk2SymbolType.dscInclude, "dscInclude"],
        [Edk2SymbolType.dscLine, "dscLine"],
        [Edk2SymbolType.infDefine, "infDefine"],
        [Edk2SymbolType.infSource, "infSource"],
        [Edk2SymbolType.infPackage, "infPackage"],
        [Edk2SymbolType.infPpi, "infPpi"],
        [Edk2SymbolType.infProtocol, "infProtocol"],
        [Edk2SymbolType.infPcd, "infPcd"],
        [Edk2SymbolType.infGuid, "infGuid"],
        [Edk2SymbolType.infDepex, "infDepex"],
        [Edk2SymbolType.infLibrary, "infLibrary"],
        [Edk2SymbolType.infBinary, "infBinary"],
        [Edk2SymbolType.infSectionLibraries, "infSectionLibraries"],
        [Edk2SymbolType.infSectionProtocols, "infSectionProtocols"],
        [Edk2SymbolType.infSectionPpis, "infSectionPpis"],
        [Edk2SymbolType.infSectionGuids, "infSectionGuids"],
        [Edk2SymbolType.infSectionPcds, "infSectionPcds"],
        [Edk2SymbolType.infSection, "infSection"],
        [Edk2SymbolType.infFunction, "infFunction"],
        [Edk2SymbolType.decSection, "decSection"],
        [Edk2SymbolType.decDefine, "decDefine"],
        [Edk2SymbolType.decPackage, "decPackage"],
        [Edk2SymbolType.decPpi, "decPpi"],
        [Edk2SymbolType.decProtocol, "decProtocol"],
        [Edk2SymbolType.decPcd, "decPcd"],
        [Edk2SymbolType.decInclude, "decIncludes"],
        [Edk2SymbolType.decLibrary, "decLibrary"],
        [Edk2SymbolType.decGuid, "decGuid"],
        [Edk2SymbolType.aslDefinitionBlock, "aslDefinitionBlock"],
        [Edk2SymbolType.aslExternal, "aslExternal"],
        [Edk2SymbolType.aslScope, "aslScope"],
        [Edk2SymbolType.aslDevice, "aslDevice"],
        [Edk2SymbolType.aslName, "aslName"],
        [Edk2SymbolType.aslMethod, "aslMethod"],
        [Edk2SymbolType.aslField, "aslField"],
        [Edk2SymbolType.aslOpRegion, "aslOpRegion"],
        [Edk2SymbolType.aslDefault, "aslDefault"],
        [Edk2SymbolType.vfrDefault, "vfrDefault"],
        [Edk2SymbolType.vfrFormset, "vfrFormset"],
        [Edk2SymbolType.vfrForm, "vfrForm"],
        [Edk2SymbolType.vfrOneof, "vfrOneof"],
        [Edk2SymbolType.vfrCheckbox, "vfrCheckbox"],
        [Edk2SymbolType.vfrString, "vfrString"],
        [Edk2SymbolType.vfrPassword, "vfrPassword"],
        [Edk2SymbolType.vfrNumeric, "vfrNumeric"],
        [Edk2SymbolType.vfrGoto, "vfrGoto"],
        [Edk2SymbolType.fdfSection, "fdfSection"],
        [Edk2SymbolType.fdfInf, "fdfInf"],
        [Edk2SymbolType.fdfDefinition, "fdfDefinition"],
        [Edk2SymbolType.fdfFile, "fdfFile"],
        [Edk2SymbolType.fdfInclude, "fdfInclude"],
        [Edk2SymbolType.condition, "condition"],
        [Edk2SymbolType.unknown, "unknown"],
    ]
);