site_name: Edk2Code Vscode Extension
theme:
  name: readthedocs
  locale: en
  custom_dir: theme/

markdown_extensions: 
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#+type:note

extra:
  generator: false

extra_css:
  - css/extra.css
  - css/codicon.min.css
extra_javascript:
  - js/popper.min.js
  - js/tippy-bundle.umd.min.js
  - js/clipboard.min.js
  - js/extra.js
  - https://buttons.github.io/buttons.js

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Getting Started: getting_started.md
  - Advanced Features: advance_features.md
  - Configuration: configuration.md
  - Troubleshooting: troubleshooting.md